//! ULID-based identifiers (`01-protocol.md` §3).
//!
//! Both serialize as their canonical 26-character Crockford base32 string.

use serde::{Deserialize, Serialize};
use ulid::Ulid;

/// A single request on a connection.
///
/// Generated by the client, echoed verbatim by the supervisor in the
/// `Response`, and used to correlate the `Authorized` / `Errored` audit record.
#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Debug, Serialize, Deserialize)]
#[serde(transparent)]
// `Default` is deliberately not implemented: a default that silently mints a
// fresh random id would be a footgun (e.g. `RequestId::default()`
// accidentally producing a new id where "no id" was intended).
pub struct RequestId(pub Ulid);

impl RequestId {
    /// Create a new unique request id (time-ordered, random suffix).
    #[allow(clippy::new_without_default)]
    pub fn new() -> Self {
        Self(Ulid::new())
    }

    /// The underlying ULID.
    pub fn as_ulid(self) -> Ulid {
        self.0
    }
}

impl std::fmt::Display for RequestId {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        self.0.fmt(f)
    }
}

/// A connection-scoped session, minted by the supervisor in `Welcome`.
#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Debug, Serialize, Deserialize)]
#[serde(transparent)]
pub struct SessionId(pub Ulid);

impl SessionId {
    /// Create a new unique session id.
    #[allow(clippy::new_without_default)]
    pub fn new() -> Self {
        Self(Ulid::new())
    }

    /// The underlying ULID.
    pub fn as_ulid(self) -> Ulid {
        self.0
    }
}

impl std::fmt::Display for SessionId {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        self.0.fmt(f)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn round_trip_through_json() {
        let id = RequestId::new();
        let s = serde_json::to_string(&id).unwrap();
        // canonical form: 26 Crockford base32 characters, plus quotes
        assert_eq!(s.len(), 28);
        let inner = &s[1..s.len() - 1];
        assert_eq!(inner.len(), 26);
        // Crockford base32: no I, L, O, U
        assert!(!inner.chars().any(|c| matches!(c, 'I' | 'L' | 'O' | 'U' | 'i' | 'l' | 'o' | 'u')));
        assert!(inner.chars().all(|c| c.is_ascii_alphanumeric()));
        let back: RequestId = serde_json::from_str(&s).unwrap();
        assert_eq!(id, back);
        // Display matches the wire form.
        assert_eq!(id.to_string(), inner);
    }

    #[test]
    fn session_id_round_trip() {
        let id = SessionId::new();
        let back: SessionId = serde_json::from_str(&serde_json::to_string(&id).unwrap()).unwrap();
        assert_eq!(id, back);
    }

    #[test]
    fn unique_and_ordered() {
        let a = RequestId::new();
        let b = RequestId::new();
        assert_ne!(a, b);
        // ULIDs are time-ordered; two generated back-to-back compare in
        // creation order (monotonicity within the same millisecond is not
        // guaranteed, so only assert inequality and total ordering).
        assert!(a < b || b < a);
    }
}
